### ISSUE TITLE
Opening example 

### ISSUE THREAD

**Issue by Pertence** [MrNothing/AI-Blocks#1]
When I open an example project, i get this:

![capture](https://user-images.githubusercontent.com/11244600/32972600-57c477e6-cbda-11e7-9658-09966aad13c7.JPG)

Is this a normal behavior?

Observation: I am running on Windows 10 64 bits.

**Comment by MrNothing** [comment]
Well it is normal but definitively unwanted, this is due to the project being created on a larger screen than yours. I will add this in the todo list.

**Comment by MrNothing** [comment]
Fixed with https://github.com/MrNothing/AI-Blocks/releases/tag/v1.4.0-beta
