### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Pertence** [MrNothing/AI-Blocks#10]
I downloaded the win32x64 version, unpacked it and ran aiblocs.exe, however a blank screen appeared like the picture below. By the way, I am using Windows 10 x64.
![capture](https://user-images.githubusercontent.com/11244600/33520153-4a131152-d79c-11e7-8558-67ed726e1a89.JPG)

**Comment by MrNothing** [comment]
Try this version: https://github.com/MrNothing/AI-Blocks/releases/tag/v1.5.2-beta
I cannot reproduce your issue on my computer. Let me know if this works for you.

**Comment by MrNothing** [comment]
OK was my bad, this release is indeed broken. Until I release a patch, use this one: https://github.com/MrNothing/AI-Blocks/releases/tag/v1.5.1-beta

**Comment by Pertence** [comment]
Thanks. You can close this issue as you wish.

**Comment by DaidoujiChen** [comment]
Hello,

The same issue on mac.
download path https://github.com/MrNothing/AI-Blocks/releases/download/v1.5.2-beta/ai-blocks-mac.zip
os version: 10.12.6
![2017-12-08 11 48 58](https://user-images.githubusercontent.com/670441/33750288-cd65ec94-dc0d-11e7-8d67-a31cd3612137.png)

**Comment by MrNothing** [comment]
@Pertence could you try the latest build? If it still does not launch, could you please give me the content of the error_log.txt file?

@DaidoujiChen for now i suggest you to launch the project from the sources for mac.
