### ISSUE TITLE
How to change python interpreter?

### ISSUE THREAD

**Issue by rh01** [MrNothing/AI-Blocks#14]
I can't run these scripts in my python environment(Anaconda 3 virtual environment, Windows) .

Thanks!

**Comment by MrNothing** [comment]
HI, check this issue:  #12 

I am working on allowing custom interpreters, until then, you can either modify the sources to set your own interpreter or wait for the next version that should implement that.

Sorry for the inconvenience.

**Comment by rh01** [comment]
Okay, I'll try it! 

Thanks for your reply!
