### ISSUE TITLE
ENOENT: no such file or directory, scandir './scripts' (v1.5.3-beta, Mac)

### ISSUE THREAD

**Issue by ansoncsh** [MrNothing/AI-Blocks#17]
Hi,

I just download the latest build (v1.5.3-beta) and build the Mac version.
I always get this error when opening a project (happens on both a new project and example project)

<img width="532" alt="screen shot 2018-09-06 at 10 50 45 am" src="https://user-images.githubusercontent.com/5925265/45132444-8e5d0500-b1c3-11e8-806b-5d6e4fc63115.png">
Would you have any advice how I should deal with it?

Thank you!

**Comment by MrNothing** [comment]
Hi, 
there are issues with the MAC release for now. The only working way to run AIBlocks from a Mac is to build if from the sources. (I dont have access to a mac myslelf). See issue #2 
Have a great day,

Boris
