### ISSUE TITLE
Cannot click script editing icon

### ISSUE THREAD

**Issue by nickleyw** [MrNothing/AI-Blocks#19]
I've been able to successfully run the auto-encoder demo (noting I did have to change the encoder input from 1024 to 784, and switch the decoder to match, with input 10, output 784). However, anytime I click the little edit script icon, what looks like a console window flashes open and then closes in like 1/10th a second... I cannot seem to be able to edit any of the scripting. Ideas?

running AI-Blocks 5.3 win32x64

Thank you.

**Comment by MrNothing** [comment]
Hi, the edit script icon runs your default application associated with .py files, you need to define it on windows (right click on any .py file, open with ...)

**Comment by nickleyw** [comment]
thanks for the response, makes sense. 
however, it seems there's some bigger issue in windows 10 at the moment preventing people from doing this with sublime text or notepad++ [https://forum.sublimetext.com/t/cannot-make-sublime-3-default-editor-windows-10-sept-2018/39426/14](url) 
guess i have some digging to do. what default app do you use?

**Comment by MrNothing** [comment]
ow, didnt know about this, I use visual studio code. I used to have sublime by default aswell (around 6 month ago) I didnt have any issues.
Regardless if you want to manually edit a built-in script you can find it in the scripts folder of AI-Blocs sources (note that It will affect all your projects that use built-in scripts).

Good luck!
