### ISSUE TITLE
Mac/Linux support

### ISSUE THREAD

**Issue by MrNothing** [MrNothing/AI-Blocks#2]
Todo: Modify ProjectRunner.js so that it becomes crossplatform when spawning the python.exe process.

**Comment by MrNothing** [comment]
Avaliable here: https://github.com/MrNothing/AI-Blocks/releases/tag/v1.4.2-beta

Has yet to be tested.

**Comment by CrypticCalamari** [comment]
Testing on Kali Linux with xfce4 window manager. When I run the project, it opens a blank window, which takes some time before anything appears. At first I didn't think it was working and closed the window, but tried again and became distracted before coming back to see everything loaded.

Perhaps a loading indicator during application startup.

As for creating a new project. I can't seem to figure out how to do this. When I select a folder and name for the project then click create under empty project, nothing seems to happen. When I click clone under the MNIST-classifier or Auto-Encoder I get this error: Failed to load example: Error: ENOENT: no such file or directory, scandir '/home/username/Testy McTestFace\'

**Comment by MrNothing** [comment]
Thank you for taking the time to test this version, I will debug it on my vm, It seems the relative path is different on linux and windows. That is the cause of your problems.

**Comment by MrNothing** [comment]
Fixed and tested for linux 64, check next release.

**Comment by MrNothing** [comment]
All versions fixed: see #8

**Comment by jmelgarmartin** [comment]
how can I launch the program on linux?

**Comment by MrNothing** [comment]
@jmelgarmartin Either build the sources or download one of the linux builds: https://github.com/MrNothing/AI-Blocks/releases

**Comment by jmelgarmartin** [comment]
I download the sorce forlinux but I can't find an executable sh or file

**Comment by MrNothing** [comment]
@jmelgarmartin The executable file is a file called AI-Blocks that you can launch using the command: 

> ./AI-Blocks
if you encouter an error, you might need to install this package:

> apt-get install libgconf-2-4

Hope this helps.

**Comment by sid-thakur** [comment]
Hello, Seems like a nice project! Looking to build and use on a Mac (Mojave OSX 10.14.6). I grabbed the source code AI-Blocks-1.5.2-beta and tried to build it per instructions in the README.md file. 
```
$ npm run
Lifecycle scripts included in aiblocs:
  start
    react-scripts start
  test
    react-scripts test --env=jsdom

available via `npm run-script`:
  run
    electron -r babel-register .
  build
    react-scripts build
  eject
    react-scripts eject
```
Tried to build build but getting following error:
```
$ npm run build

> aiblocs@0.1.0 build /Users/sid/Documents/Thinci/Projects/Experiments/visual_editor/AI-Blocks-1.5.2-beta/Sources
> react-scripts build

Could not find a required file.
  Name: index.html
  Searched in: /Users/x/Documents/AI-Blocks-1.5.2-beta/Sources/public
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aiblocs@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aiblocs@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/x/.npm/_logs/2019-09-25T15_38_35_128Z-debug.log
```
I am missing the `Sources/public` folder, but isn't it the purpose of `npm run build` to create the outputs and build the `public` folder? Thanks for your help!

**Comment by MrNothing** [comment]
Hi, I suggest simply cloning the project and launching from the Sources
folder, by typing npm run test.
Most packages are now getting old and may be deprecated.

Let me know if you still have the same problem.

Have a nice day!

**Comment by sid-thakur** [comment]
Thanks @MrNothing for the quick response.

Cloned the repository and installed npm packages.

Ran the following:
```
$ npm run test

> aiblocs@0.1.5 test /Users/x/Documents/AI-Blocks/Sources
> electron -r babel-register 
```
The app launches but I see a blank app screen.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/5922613/65621961-b831c700-df92-11e9-8e3e-db6563b860d7.png">

Thanks.

**Comment by MrNothing** [comment]
Can you open the console? in your menu, view->developper tools then open
the console tab.

**Comment by sid-thakur** [comment]
Here's the console output:
![image](https://user-images.githubusercontent.com/5922613/65712974-272c2000-e066-11e9-99df-24d5542be740.png)

**Comment by MrNothing** [comment]
I will work on updating the project to webpack, the libraries are getting
old, I will tell you when the new version is up.

**Comment by MrNothing** [comment]
@sid-thakur Try pulling the latest version again, it should run properly.

**Comment by sid-thakur** [comment]
Thanks @MrNothing I was able to see the interface, but looks like reference to base/parent folder is missing. Clicking on the icon 'open folder' causes some exceptions in the console. Namely, 
Same happens when I try to ether clone a project or create an empty project. Thanks.

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/5922613/66620467-94839900-ebae-11e9-988a-65881789898e.png">

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/5922613/66620550-eaf0d780-ebae-11e9-9c2e-ab58a69a61c4.png">

**Comment by MrNothing** [comment]
Hi, these are some mac specific bugs with electron, I will fix them asap
and let you know.

Have a great day!

**Comment by MrNothing** [comment]
Hi, this was due to a newer version of electron, i apologize for that.
Everything should be working now, just pull the latest changes.

**Comment by sid-thakur** [comment]
Thanks! I was able to run the application and see expected behavior on my Mac (Mojave). Thanks for all the help!

<img width="847" alt="image" src="https://user-images.githubusercontent.com/5922613/66857913-3c55e980-ef56-11e9-9d63-71b6524f8cd2.png">
