### ISSUE TITLE
Problem using tensorflow

### ISSUE THREAD

**Issue by Pertence** [MrNothing/AI-Blocks#7]
When I try to run an project, I get this error: 
"C:\Users\Augusto\AppData\Local\Temp/main.py", line 2, in <module>import tensorflow as tf
ImportError: No module named tensorflow."
However, I can import this module with no problem, using JupyterLab with an conda environment with tensorflow package installed. 
Can you help me? Please.

**Comment by MrNothing** [comment]
The conda environement is an isolated instance. The program runs tensorflow from cmd.exe. Have you tried importing tensorflow from a regular command line? If it does not work, I suggest installing tensorflow the regular way:
> pip install tensorflow 
or 
> pip-install tensorflow-gpu

Let me know if this fixes your issue.

**Comment by Pertence** [comment]
It may take a while test. First, I have to, properly, configure python 3.5 on my machine.

**Comment by MrNothing** [comment]
I'm closing this, let me know if you still have issues when tensorflow is installed.
